remove matrix strategy & add duplicate job definitions for 1es pools

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -152,14 +152,31 @@ jobs:
 
   test_ubuntu_emu_ddi:
 
-    name: test_ubuntu_emu_ddi (${{ matrix.runner }})
+    runs-on: ubuntu-24.04
 
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [ubuntu-24.04, azihsm-arm64-gh-ubuntu2404-pool]
+    defaults:
+      run:
+        working-directory: .
 
-    runs-on: ${{ matrix.runner }}
+    steps:
+    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+    - uses: ./.github/actions/ubuntu-setup
+    - name: Run emu DDI tests
+      id: test-emu-ddi
+      run: cargo xtask precheck --nextest --package azihsm_ddi_mbor_types --features emu --test azihsm_ddi_tests --profile ci-emu-ddi
+      continue-on-error: true
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-emu-ddi.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
+  test_azihsm-arm64-gh-ubuntu2404-pool_emu_ddi:
+
+    runs-on: azihsm-arm64-gh-ubuntu2404-pool
 
     defaults:
       run:
