break out azihsm_api_tests package into new test job

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -55,6 +55,102 @@ jobs:
     - name: Cargo Clippy
       run: cargo xtask precheck --clippy
 
+  test_ubuntu_mock_coverage:
+
+    runs-on: ubuntu-24.04
+
+    defaults:
+      run:
+        working-directory: .
+
+    steps:
+    - uses: actions/checkout@v6
+    - name: Install apt packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y pkg-config libbsd-dev
+    - name: Restore Cargo cache
+      id: cargo-cache
+      uses: actions/cache/restore@v5
+      with:
+        path: |
+          ~/.cargo/bin/
+          ~/.cargo/registry/index/
+          ~/.cargo/registry/cache/
+          ~/.cargo/git/db/
+        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
+    - name: Setup on cache miss
+      if: steps.cargo-cache.outputs.cache-hit != 'true' 
+      run: cargo xtask setup
+    - name: Run all mock tests (except azihsm_api_tests) with code coverage
+      id: test-mock-coverage
+      run: cargo xtask precheck --coverage --exclude azihsm_api_tests --features mock --profile ci-mock
+      continue-on-error: true
+    - name: Upload coverage report
+      uses: actions/upload-artifact@v7
+      with:
+        name: coverage-report-ubuntu
+        path: ./target/reports/
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Code Coverage Summary Report
+      if: ${{ steps.test-mock-coverage.outcome == 'success' }}
+      run: cargo xtask precheck --coverage-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-mock-coverage.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
+  test_ubuntu_api_coverage:
+
+    runs-on: ubuntu-24.04
+
+    defaults:
+      run:
+        working-directory: .
+
+    steps:
+    - uses: actions/checkout@v6
+    - name: Install apt packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y pkg-config libbsd-dev
+    - name: Restore Cargo cache
+      id: cargo-cache
+      uses: actions/cache/restore@v5
+      with:
+        path: |
+          ~/.cargo/bin/
+          ~/.cargo/registry/index/
+          ~/.cargo/registry/cache/
+          ~/.cargo/git/db/
+        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
+    - name: Setup on cache miss
+      if: steps.cargo-cache.outputs.cache-hit != 'true' 
+      run: cargo xtask setup
+    - name: Run azihsm_api_tests with code coverage
+      id: test-api-coverage
+      run: cargo xtask precheck --coverage -p azihsm_api_tests --profile ci-azihsm-api-tests
+      continue-on-error: true
+    - name: Upload coverage report
+      uses: actions/upload-artifact@v7
+      with:
+        name: coverage-report-ubuntu
+        path: ./target/reports/
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Code Coverage Summary Report
+      if: ${{ steps.test-api-coverage.outcome == 'success' }}
+      run: cargo xtask precheck --coverage-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-api-coverage.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
   test_ubuntu_misc:
 
     runs-on: ubuntu-24.04
@@ -79,7 +175,7 @@ jobs:
           ~/.cargo/registry/cache/
           ~/.cargo/git/db/
         key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
-    - name: Setup
+    - name: Setup on cache miss
       if: steps.cargo-cache.outputs.cache-hit != 'true' 
       run: cargo xtask setup
     - name: SDK Run all mock tests table-4
@@ -109,106 +205,6 @@ jobs:
       run: |
         echo "One or more tests failed."
         exit 1
-
-  test_ubuntu_mock_coverage:
-
-    runs-on: ubuntu-24.04
-
-    defaults:
-      run:
-        working-directory: .
-
-    steps:
-    - uses: actions/checkout@v6
-    - name: Install apt packages
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y pkg-config libbsd-dev
-    - name: Restore Cargo cache
-      id: cargo-cache
-      uses: actions/cache/restore@v5
-      with:
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
-    - name: Setup
-      if: steps.cargo-cache.outputs.cache-hit != 'true' 
-      run: cargo xtask setup
-    # - name: Run all mock tests with code coverage
-    #   id: test-mock-coverage
-    #   run: cargo xtask precheck --coverage --features mock --profile ci-mock
-    #   continue-on-error: true
-
-    # TEMPORARIY BREAK OUT BY BINARY ID TO ASSESS RUNTIMES - REMOVE ONCE FIXED
-    - name: azihsm_api
-      id: azihsm_api
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_api_native
-      id: azihsm_api_native
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api_native)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_api_tests
-      id: azihsm_api_tests
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api_tests*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_crypto
-      id: azihsm_crypto
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_crypto)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_emu
-      id: azihsm_ddi_emu
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_emu)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_mbor_codec
-      id: azihsm_ddi_mbor_codec
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_mbor_*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_tbor_codec
-      id: azihsm_ddi_tbor_codec
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_tbor_*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_core_crypto_key_report
-      id: azihsm_fw_core_crypto_key_report
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_core_crypto_key_report)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_ddi_mbor
-      id: azihsm_fw_ddi_mbor
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_ddi_mbor*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_ddi_tbor
-      id: azihsm_fw_ddi_tbor
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_ddi_tbor*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_hsm
-      id: azihsm_fw_hsm
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_hsm*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_tpm
-      id: azihsm_tpm
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_tpm)' --features mock --profile ci-mock
-      continue-on-error: true
-    # END TEMP BREAKOUT
-    
-    - name: Upload coverage report
-      uses: actions/upload-artifact@v7
-      with:
-        name: coverage-report-ubuntu
-        path: ./target/reports/
-    - name: Generate nextest report
-      id: nextest-report
-      run: cargo xtask precheck --nextest-report
-    # - name: Code Coverage Summary Report
-    #   if: ${{ steps.test-mock-coverage.outcome == 'success' }}
-    #   run: cargo xtask precheck --coverage-report
-    # - name: Fail if any tests failed
-    #   if: ${{ steps.test-mock-coverage.outcome == 'failure' }}
-    #   run: |
-    #     echo "One or more tests failed."
-    #     exit 1
 
   build_windows:
 
@@ -246,42 +242,6 @@ jobs:
     - name: Cargo Clippy
       run: cargo xtask precheck --clippy
 
-  test_windows_misc:
-
-    runs-on: windows-2025-vs2026
-
-    defaults:
-      run:
-        working-directory: .
-
-    steps:
-    - uses: actions/checkout@v6
-    - name: Restore Cargo cache
-      id: cargo-cache
-      uses: actions/cache/restore@v5
-      with:
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
-    - name: Setup
-      if: steps.cargo-cache.outputs.cache-hit != 'true' 
-      run: cargo xtask setup
-    - name: Run resiliency fault injection tests with code coverage
-      id: test-res-fault
-      run: cargo xtask precheck --coverage --package azihsm_api_tests --features mock,res-test -E 'test(resiliency::fault_injection::)' --profile ci-mock
-      continue-on-error: true
-    - name: Generate nextest report
-      id: nextest-report
-      run: cargo xtask precheck --nextest-report
-    - name: Fail if any tests failed
-      if: ${{ steps.test-res-fault.outcome == 'failure' }}
-      run: |
-        echo "One or more tests failed."
-        exit 1
-
   test_windows_mock_coverage:
 
     runs-on: windows-2025-vs2026
@@ -305,61 +265,10 @@ jobs:
     - name: Setup on cache miss
       if: steps.cargo-cache.outputs.cache-hit != 'true'
       run: cargo xtask precheck --setup
-    # - name: Run all mock tests with code coverage
-    #   id: test-mock-coverage
-    #   run: cargo xtask precheck --coverage --features mock --profile ci-mock
-    #   continue-on-error: true
-
-    # TEMPORARIY BREAK OUT BY BINARY ID TO ASSESS RUNTIMES - REMOVE ONCE FIXED
-    - name: azihsm_api
-      id: azihsm_api
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api)' --features mock --profile ci-mock
+    - name: Run all mock tests (except azihsm_api_tests) with code coverage
+      id: test-mock-coverage
+      run: cargo xtask precheck --coverage --exclude azihsm_api_tests --features mock --profile ci-mock
       continue-on-error: true
-    - name: azihsm_api_native
-      id: azihsm_api_native
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api_native)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_api_tests
-      id: azihsm_api_tests
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_api_tests*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_crypto
-      id: azihsm_crypto
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_crypto)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_emu
-      id: azihsm_ddi_emu
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_emu)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_mbor_codec
-      id: azihsm_ddi_mbor_codec
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_mbor_*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_ddi_tbor_codec
-      id: azihsm_ddi_tbor_codec
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_ddi_tbor_*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_core_crypto_key_report
-      id: azihsm_fw_core_crypto_key_report
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_core_crypto_key_report)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_ddi_mbor
-      id: azihsm_fw_ddi_mbor
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_ddi_mbor*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_ddi_tbor
-      id: azihsm_fw_ddi_tbor
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_ddi_tbor*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_fw_hsm
-      id: azihsm_fw_hsm
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_fw_hsm*)' --features mock --profile ci-mock
-      continue-on-error: true
-    - name: azihsm_tpm
-      id: azihsm_tpm
-      run: cargo xtask precheck --coverage -E 'binary_id(azihsm_tpm)' --features mock --profile ci-mock
-      continue-on-error: true
-    # END TEMP BREAKOUT
     - name: Upload coverage report
       uses: actions/upload-artifact@v7
       with:
@@ -368,11 +277,91 @@ jobs:
     - name: Generate nextest report
       id: nextest-report
       run: cargo xtask precheck --nextest-report
-    # - name: Code Coverage Summary Report
-    #   if: ${{ steps.test-mock-coverage.outcome == 'success' }}
-    #   run: cargo xtask precheck --coverage-report
-    # - name: Fail if any tests failed
-    #   if: ${{ steps.test-mock-coverage.outcome == 'failure' }}
-    #   run: |
-    #     echo "One or more tests failed."
-    #     exit 1
+    - name: Code Coverage Summary Report
+      if: ${{ steps.test-mock-coverage.outcome == 'success' }}
+      run: cargo xtask precheck --coverage-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-mock-coverage.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
+  test_windows_api_coverage:
+
+    runs-on: windows-2025-vs2026
+
+    defaults:
+      run:
+        working-directory: .
+
+    steps:
+    - uses: actions/checkout@v6
+    - name: Restore Cargo cache
+      id: cargo-cache
+      uses: actions/cache/restore@v5
+      with:
+        path: |
+          ~/.cargo/bin/
+          ~/.cargo/registry/index/
+          ~/.cargo/registry/cache/
+          ~/.cargo/git/db/
+        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
+    - name: Setup
+      if: steps.cargo-cache.outputs.cache-hit != 'true' 
+      run: cargo xtask setup
+    - name: Run azihsm_api_tests with code coverage
+      id: test-api-coverage
+      run: cargo xtask precheck --coverage -p azihsm_api_tests --profile ci-azihsm-api-tests
+      continue-on-error: true
+    - name: Upload coverage report
+      uses: actions/upload-artifact@v7
+      with:
+        name: coverage-report-windows
+        path: ./target/reports/
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Code Coverage Summary Report
+      if: ${{ steps.test-api-coverage.outcome == 'success' }}
+      run: cargo xtask precheck --coverage-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-api-coverage.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
+  test_windows_misc:
+
+    runs-on: windows-2025-vs2026
+
+    defaults:
+      run:
+        working-directory: .
+
+    steps:
+    - uses: actions/checkout@v6
+    - name: Restore Cargo cache
+      id: cargo-cache
+      uses: actions/cache/restore@v5
+      with:
+        path: |
+          ~/.cargo/bin/
+          ~/.cargo/registry/index/
+          ~/.cargo/registry/cache/
+          ~/.cargo/git/db/
+        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY_ID }}
+    - name: Setup on cache miss
+      if: steps.cargo-cache.outputs.cache-hit != 'true' 
+      run: cargo xtask setup
+    - name: Run resiliency fault injection tests with code coverage
+      id: test-res-fault
+      run: cargo xtask precheck --coverage --package azihsm_api_tests --features mock,res-test -E 'test(resiliency::fault_injection::)' --profile ci-mock
+      continue-on-error: true
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-res-fault.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
