[build] add jobs targeting 1ES hosted pool (#560)
* update workflows to target 1ES hosted pool

* update remaining jobs still targetting github-hosted runners

* point to deployed image

* try pointing to deployed image without using matrix strategy

* add simple job to test 1ES deployment

* try w/ Scale Set API

* try w/ different format

* try suggested yml

* attempt 2

* remove other workflows to reduce logging noise

* attempt 3

* attempt 4

* Refactor workflow runs-on syntax and echo command

Updated the GitHub Actions workflow to use a more structured 'runs-on' syntax and changed the echo command output.

* Update GitHub Actions runner pool name

Updating to correct pool name

* Update echo message in test workflow to differentiate

* Refactor runs-on syntax in test.yml

* Update runner label in GitHub Actions workflow

* Update test.yml

* Update runner configuration in test workflow

* Revert "remove other workflows to reduce logging noise"

This reverts commit b134a78fc60b62ff47367854f65c9125d8b08a46.

* update ubuntu workflows to target azihsm-arm64-gh-pool-westus2-New self-hosted runner

* re-delete workflows to simplify logging

* target azihsm-x64-gh-westus2-pool in coverage.yml

* force cache miss in coverage.yml to test behavior w/ full setup

* try image override in coverage_windows job

* attempt 2 at image override in coverage_windows job

* Update runs-on configuration in coverage.yml

* Update runs-on configuration in coverage.yml

* Update failure message in coverage workflow

* Update coverage.yml

* Update coverage.yml

* Revert "re-delete workflows to simplify logging"

This reverts commit 70496421f2c46c9f24c0b3ae1a1b889448968245.

* add test_ubuntu_emu_ddi_arm64

* revert target runners in applicable jobs

* fix error: linker cc not found

* override CACHE_KEY_ID in test_ubuntu_emu_ddi_arm64 to force cache miss for that specific job

* fix Error: No OpenSSL 3.x installation found.

* update target pool for coverage_windows

* test windows images

* Update test.yml

* update target pool for coverage_windows

* create test caches for 1es runners

* use test cache in coverage.yml

* remove test.yml & opt for matrix strategy instead of duplicated job definitions to support arm64 runner

* add pull_request trigger to test caching behavior

* add rustup install step to arm64 create_new_cache.yml job

* fix error: linker cc not found

* fix Error: No OpenSSL 3.x installation found.

* name caches by runner name instead of runner os

* load cache based on runner.name & remove pull_request trigger from create_new_cache.yml

* update cache id

* name cache by os & arch

* update CACHE_KEY_ID to test id

* fix error: no such command: llvm-cov

* update CACHE_KEY_ID to test id

* reset CACHE_KEY_ID & remove pull_request trigger from create_new_cache.yml

* CR feedback & add temporary test failure

* remove temporary test failure

* remove continue-on-error keyboard in rust.yml & coverage.yml

* remove JOB_ID env var definition

* copilot feedback

* remove matrix strategy & add duplicate job definitions for 1es pools

* copilot feedback

* copilot feedback

---------

Co-authored-by: CPiccini <47435428+CPiccini@users.noreply.github.com>
Co-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -174,6 +174,30 @@ jobs:
         echo "One or more tests failed."
         exit 1
 
+  test_azihsm-arm64-gh-ubuntu2404-pool_emu_ddi:
+
+    runs-on: azihsm-arm64-gh-ubuntu2404-pool
+
+    defaults:
+      run:
+        working-directory: .
+
+    steps:
+    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+    - uses: ./.github/actions/ubuntu-setup
+    - name: Run emu DDI tests
+      id: test-emu-ddi
+      run: cargo xtask precheck --nextest --package azihsm_ddi_mbor_types --features emu --test azihsm_ddi_tests --profile ci-emu-ddi
+      continue-on-error: true
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-emu-ddi.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
+
   build_windows:
 
     runs-on: windows-2025-vs2026
