[build] report test totals in workflow summary (#108)

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -54,16 +54,30 @@ jobs:
     - name: Cargo Clippy
       run: cargo xtask precheck --clippy
     - name: SDK Run all mock tests table-4
-      run: cargo xtask precheck --nextest --package azihsm_ddi --features mock,table-4
+      id: test-mock-table-4
+      run: cargo xtask precheck --nextest --package azihsm_ddi --features mock,table-4 --profile ci-mock-table-4
+      continue-on-error: true
     - name: SDK Run all mock tests table-64
-      run: cargo xtask precheck --nextest --package azihsm_ddi --features mock,table-64
+      id: test-mock-table-64
+      run: cargo xtask precheck --nextest --package azihsm_ddi --features mock,table-64 --profile ci-mock-table-64
+      continue-on-error: true
     - name: Run all mock tests with code coverage
+      id: test-mock-coverage
       run: cargo xtask precheck --coverage
+      continue-on-error: true
     - name: Upload coverage report
       uses: actions/upload-artifact@v4
       with:
         name: coverage-report-ubuntu
         path: ./target/reports/
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-mock-coverage.outcome == 'failure' || steps.test-mock-table-4.outcome == 'failure' || steps.test-mock-table-64.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
   
   build_windows:
 
@@ -101,9 +115,19 @@ jobs:
     - name: Cargo Clippy
       run: cargo xtask precheck --clippy
     - name: Run all mock tests with code coverage
+      id: test-mock-coverage
       run: cargo xtask precheck --coverage
+      continue-on-error: true
     - name: Upload coverage report
       uses: actions/upload-artifact@v4
       with:
         name: coverage-report-windows
         path: ./target/reports/
+    - name: Generate nextest report
+      id: nextest-report
+      run: cargo xtask precheck --nextest-report
+    - name: Fail if any tests failed
+      if: ${{ steps.test-mock-coverage.outcome == 'failure' }}
+      run: |
+        echo "One or more tests failed."
+        exit 1
